version: '2'
services:
 flink-master:
   image: bde2020/flink-master:1.14.2-hadoop3.2
   hostname: flink-master
   container_name: flink-master
   ports:
     - "8080:8080"
     - "8081:8081"
   volumes: 
     - .:/opt/flink-dataS

 flink-worker-1:
   image: bde2020/flink-worker:1.14.2-hadoop3.2
   hostname: flink-worker-1
   container_name: flink-worker-1
   environment:
     - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
   depends_on:
      - flink-master
   volumes: 
     - .:/opt/flink-data

 flink-worker-2:
   image: bde2020/flink-worker:1.14.2-hadoop3.2
   hostname: flink-worker-2
   container_name: flink-worker-2
   environment:
     - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
   depends_on:
      - flink-master
   volumes: 
     - .:/opt/flink-data

 flink-worker-3:
   image: bde2020/flink-worker:1.14.2-hadoop3.2
   hostname: flink-worker-3
   container_name: flink-worker-3
   environment:
     - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
   depends_on:
     - flink-master
   volumes:
     - .:/opt/flink-data