version: '2'
services:
 flink-master:
   image: bde2020/flink-master:1.14.2-hadoop3.2
   hostname: flink-master
   container_name: flink-master
#   networks:
#     - hadoop
   ports:
     - "8080:8080"
     - "8081:8081"
   volumes: 
     - .:/opt/flink-data

 flink-worker-1:
   image: bde2020/flink-worker:1.14.2-hadoop3.2
   hostname: flink-worker-1
   container_name: flink-worker-1
#   networks:
#     - hadoop
   environment:
     - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
#     - FLINK_NUM_TASK_SLOTS=2
   depends_on:
      - flink-master
   volumes: 
     - .:/opt/flink-data

 flink-worker-2:
   image: bde2020/flink-worker:1.14.2-hadoop3.2
   hostname: flink-worker-2
   container_name: flink-worker-2
#   networks:
#     - hadoop
   environment:
     - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
#     - FLINK_NUM_TASK_SLOTS=2
   depends_on:
      - flink-master
   volumes: 
     - .:/opt/flink-data

#networks:
#  default:
#    external:
#      name: hadoop