version: '2.1'
networks:
  pulsar:
    driver: bridge

services:
  zookeper:
    hostname: zookeper
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - pulsar
    ports:
      - 2181:2181
    volumes:
      - .:/opt/pulsar-data

  bookkeeper:
    hostname: bookkeeper
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - pulsar
    ports:
      - 3181:3181
    volumes:
      - .:/opt/pulsar-data

  broker:
    hostname: broker
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - pulsar
    ports:
      - 8080:8080
      - 6650:6650
    volumes:
      - .:/opt/pulsar-data
